language: python
python:
  - '3.6'
install:
  - 'pip install pipenv'
  - 'pip install coveralls'
  - 'pipenv install'
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE bookworm;" -U postgres
script:
  - 'cd bookworm/'
  - 'python manage.py makemigrations'
  - 'python manage.py migrate'
  - 'python manage.py test -v 2'
after_success:
  - coveralls
