# Generated by Django 2.1.7 on 2019-03-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('synopsis', models.CharField(blank=True, default='', max_length=300)),
                ('category', models.CharField(blank=True, default='', max_length=300)),
                ('read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
